### ISSUE TITLE
Opening REI configs crash game. Possibly Modmenu too

### ISSUE THREAD

**Issue by Laifsyn** [The-Fireplace-Minecraft-Mods/Fireplace-Lib#49]
### Mod Version

7.0.0+1.18.2

### What mod loader(s) are you seeing the problem on?

Fabric

### Mod Loader Version

0.14.8

### Problem Description

Having FireLib 7.0.0 will cause game to crash when opening REI's config
```less
[20:02:20] [Render thread/ERROR]: Mixin apply for mod fireplacelib failed fireplacelib.fabric.mixins.json:clothconfig.DynamicEntryListWidgetMixin from mod fireplacelib -> me.shedaniel.clothconfig2.gui.widget.DynamicEntryListWidget: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on swapEntriesBeforeRender could not find any targets matching 'render' in me.shedaniel.clothconfig2.gui.widget.DynamicEntryListWidget. Using refmap Fireplace-Lib-Fabric-refmap.json [PREINJECT Applicator Phase -> fireplacelib.fabric.mixins.json:clothconfig.DynamicEntryListWidgetMixin from mod fireplacelib -> Prepare Injections ->  -> handler$dhe000$swapEntriesBeforeRender(Lnet/minecraft/class_4587;IIFLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on swapEntriesBeforeRender could not find any targets matching 'render' in me.shedaniel.clothconfig2.gui.widget.DynamicEntryListWidget. Using refmap Fireplace-Lib-Fabric-refmap.json [PREINJECT Applicator Phase -> fireplacelib.fabric.mixins.json:clothconfig.DynamicEntryListWidgetMixin from mod fireplacelib -> Prepare Injections ->  -> handler$dhe000$swapEntriesBeforeRender(Lnet/minecraft/class_4587;IIFLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.Inj
```
[2022-07-01-1.log](https://github.com/The-Fireplace-Minecraft-Mods/Fireplace-Lib/files/9032156/2022-07-01-1.log)

**Comment by The-Fireplace** [comment]
What Cloth Config version?

**Comment by Laifsyn** [comment]
cloth-config-6.2.57-fabric

**Comment by Laifsyn** [comment]
Let me see if `cloth-config-6.2.62-fabric.jar` fixes it then

**Comment by Laifsyn** [comment]
[crash-2022-07-01_21.10.24-client.txt](https://github.com/The-Fireplace-Minecraft-Mods/Fireplace-Lib/files/9032245/crash-2022-07-01_21.10.24-client.txt)
Seems that 7.0.0 is crashing minecraft before it even starts now
[latest.log](https://github.com/The-Fireplace-Minecraft-Mods/Fireplace-Lib/files/9032247/latest.log)

**Comment by The-Fireplace** [comment]
7.0.1 will fix this, testing out one more fix to go with it then I plan to get that released.

**Comment by The-Fireplace** [comment]
If that crash before the game starts persists, please report it to the Annotated DI issue tracker.

**Comment by The-Fireplace** [comment]
Fireplace Lib 7.0.1 released
